import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex items-center flex-col bg-base-100 overflow-y-hidden">
        <ToastContainer position="top-center" autoClose={2000} />;
        <div className="w-full lg:w-1/2 relative">{children}</div>
      </body>
    </html>
  );
}
